development:
  api_key: 183175721720888
  secret_key: 0c81fb1daab4b802a46404c3aec7adfb
  callback_url: http://127.0.0.1:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 183175721720888
  secret_key: 0c81fb1daab4b802a46404c3aec7adfb
  callback_url: http://www.facebook-connect-demo.com
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0